[WIP] Refactoring
wearerequired/digest pull request #18
Opened 2018-09-30 13:10 UTC by swissspidy

* More modern syntax
* Use single namespace file instead of god class

2020-12-18 11:47 UTC, grappler commented
Test Email mit Kommentar und Passwort zurücksetzten.
![image](https://user-images.githubusercontent.com/1785641/102611367-0e0e0400-412f-11eb-89f3-5c84b0d9e38a.png)

2020-12-18 13:00 UTC, ocean90 commented
Can you set up the [linting workflow](https://github.com/wearerequired/.github/blob/master/workflow-templates/linting.yml) (without eslint/stylelint) please?

2020-12-18 13:59 UTC, grappler commented
> Can you set up the linting workflow (without eslint/stylelint) please?

You mean deactivate eslint/stylelint or create a separate workflow for them?

2020-12-18 14:06 UTC, ocean90 commented
Ah, I thought the plugin has no CSS/JS files. In this case including the workflow as is would be nice.

2020-12-18 14:32 UTC, grappler commented
I have added it but it has not triggered. There are a few other changes that I would like to make like remove grunt but I plan to do that in a separate PR.

2020-12-18 15:05 UTC, ocean90 commented
I don't know why it doesn't run. 😞

2020-12-18 15:07 UTC, grappler commented
It might only run when creating a PR. The other task runs on push.

2020-12-18 15:25 UTC, required-com commented
`pull_request` should also include the `synchronized` event which is for every new commit on a PR.

2020-12-18 15:35 UTC, ocean90 commented
`pull_request` doesn't run if the PR has merge conflicts…

2020-12-22 07:38 UTC, grappler commented
@ocean90 I have fixed most of the issues. There are only "2 errors and 8 warnings" left. I am not sure what to do with them. Would love to have your feedback.

2020-12-22 08:09 UTC, ocean90 requested changes
The two errors are due to the incorrect `@param` tag.

For the `current_time()` warnings we'd have to check each usage whether the current time in UTC or in the current timezone needs to be used. If UTC is fine we can switch to `time()`. The others can be ignored with the `phpcs:ignore` comment which should also explain why it's ignored.

2020-12-22 08:09 UTC, ocean90 commented on inc/Message/Section.php
> +	 * @param \WP_User $user The current user.
```suggestion
	 * @param \WP_User|null $user The current user.
```

2020-12-22 08:09 UTC, ocean90 commented on inc/Message/CoreUpdate.php
> +	 * @param \WP_User $user The current user.
```suggestion
	 * @param \WP_User|null $user The current user.
```

2020-12-22 08:33 UTC, grappler commented
Thanks @ocean90!

I have changed all of the times to UTC. There maybe an issue for the first emails after upgrading. I am not sure how best to mitigate this.

2020-12-23 09:01 UTC, ocean90 requested changes

2020-12-23 09:01 UTC, ocean90 commented on inc/Message/CoreUpdate.php
> +	 * @param string        $event   The current event.
```suggestion
	 * @param array         $entries The core update entries.
	 * @param \WP_User|null $user    The current user.
	 * @param string        $event   The current event.
```

2020-12-23 09:01 UTC, ocean90 commented on template-tags/pluggable.php
> +			$switched_locale = switch_to_locale( get_locale() );
This function was introduced in WordPress 4.7.0, but the current plugin requirement is 4.4.0. Let's update the "Requires at least" parameter.

2020-12-23 09:01 UTC, ocean90 commented on digest.php
>   * Domain Path: /languages
The updated PHP and WP requirements need to be added to the [plugin headers](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/#header-fields).

2020-12-23 09:01 UTC, ocean90 commented on inc/namespace.php
> +}
```suggestion
```

This can be removed once the WP requirement has been raised to 4.7.

2021-01-07 15:33 UTC, ocean90 approved these changes

2021-01-07 15:34 UTC, ocean90 approved these changes

2021-01-07 15:34 UTC, ocean90 commented on phpcs.xml.dist
> +		<!-- Not compatable with PHP 5.6 -->
```suggestion
		<!-- Not compatible with PHP 5.6 -->
```

2021-01-07 15:46 UTC, merged